// USER
export const AUTH_USER = 'AUTH_USER';
export const REG_USER = 'REG_USER';
export const SIGNOUT = 'SIGNOUT';
export const AUTH_CHECK = 'AUTH_CHECK';
export const USER_EDIT = 'USER_EDIT';

// REQUESTS
export const IS_LOADING_TRUE = 'IS_LOADING_TRUE';
export const IS_LOADING_FALSE = 'IS_LOADING_FALSE';

// DATA
export const GET_MOVIES_FOR_MAIN = 'GET_MOVIES_FOR_MAIN';
export const GET_GENRES = 'GET_GENRES';
export const RESET_LIST = 'RESET_LIST';
export const GET_SEARCHED = 'GET_SEARCHED'
export const SET_FAVORITES = 'SET_FAVORITES'
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES'
export const SET_GENRE_MOVIES = 'SET_GENRE_MOVIES'
export const SET_REVIEWS = 'SET_REVIEWS'
export const ADD_REVIEW = 'ADD_REVIEW'
export const GET_CATEGORIES_WITH_MOVIES = 'GET_CATEGORIES_WITH_MOVIES'

// SUBSRIBES
export const SET_SUBSCIBE = 'SET_SUBSCRIBE'
export const SET_OPEN_SEARCH = 'SET_OPEN_SEARCH'

// LIKES
export const LIKE_TOGGLE = 'LIKE_TOGGLE';
